version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  customers-service:
    build: ./customers
    container_name: customers-service
    ports:
      - "3001:3001"
    env_file:
      - ./customers/.env
    depends_on:
      - mongo

  products-service:
    build: ./products
    container_name: products-service
    ports:
      - "3002:3002"
    env_file:
      - ./products/.env
    depends_on:
      - mongo

  orders-service:
    build: ./orders
    container_name: orders-service
    ports:
      - "3003:3003"
    env_file:
      - ./orders/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
