version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  mongo-customers:
    image: mongo
    container_name: mongo-customers
    ports:
      - "27017:27017"
    volumes:
      - mongo-customers-data:/data/db
    networks:
      - backend

  mongo-orders:
    image: mongo
    container_name: mongo-orders
    ports:
      - "27018:27017"  # Expose a different port to avoid conflicts
    volumes:
      - mongo-orders-data:/data/db
    networks:
      - backend

  mongo-products:
    image: mongo
    container_name: mongo-products
    ports:
      - "27019:27017"  # Expose a different port to avoid conflicts
    volumes:
      - mongo-products-data:/data/db
    networks:
      - backend

  init-customer:
    build:
      context: ./init/customer
    container_name: mongo-init-customer
    depends_on:
      - mongo-customers
    env_file:
      - ./.env
    environment:
      MONGO_URI_CUSTOMER: ${MONGO_URI_CUSTOMER}
    networks:
      - backend

  init-order:
    build:
      context: ./init/order
    container_name: mongo-init-order
    depends_on:
      - mongo-orders
    env_file:
      - ./.env
    environment:
      MONGO_URI_ORDER: ${MONGO_URI_ORDER}
    networks:
      - backend

  init-product:
    build:
      context: ./init/product
    container_name: mongo-init-product
    depends_on:
      - mongo-products
    env_file:
      - ./.env
    environment:
      MONGO_URI_PRODUCT: ${MONGO_URI_PRODUCT}
    networks:
      - backend

  customers-service:
    build: ./customers
    container_name: customers-service
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      MONGO_URL: ${MONGO_URI_CUSTOMER}
    depends_on:
      - mongo-customers
      - rabbitmq
    networks:
      - backend
      
  orders-service:
    build: ./orders
    container_name: orders-service
    ports:
      - "3003:3003"
    env_file:
      - ./.env
    environment:
      MONGO_URL: ${MONGO_URI_ORDER}
    depends_on:
      - mongo-orders
      - rabbitmq
    networks:
      - backend

  products-service:
    build: ./products
    container_name: products-service
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    environment:
      MONGO_URL: ${MONGO_URI_PRODUCT}
    depends_on:
      - mongo-products
      - rabbitmq
    networks:
      - backend

volumes:
  mongo-customers-data:
  mongo-products-data:
  mongo-orders-data:

networks:
  backend:
